"""Add excel_workflow_sessions table

Revision ID: d036de8a5903
Revises: 8ea178904eb8
Create Date: 2025-09-01 18:17:02.256236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd036de8a5903'
down_revision = '8ea178904eb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_workflow_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('results_file_path', sa.Text(), nullable=True),
    sa.Column('total_keywords', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excel_workflow_sessions')
    # ### end Alembic commands ###
